baseurl = "https://ndqonline.netlify.com"
title = "Nguyen Dang Quang"
theme = "noteworthy"

[Params]
    mainSections = ["post"]
    intro = true
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"